// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY46d_yLZRGNRzhGOJHbg3nWWgBVoj52M',
    appId: '1:513129336045:web:77d17aaf14ce0e469210e4',
    messagingSenderId: '513129336045',
    projectId: 'alesco-hotelio',
    authDomain: 'alesco-hotelio.firebaseapp.com',
    storageBucket: 'alesco-hotelio.appspot.com',
    measurementId: 'G-2YEKBJ20V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9GGJjUlwxEkAVXCA_Cx_DVKfHDF9YKfU',
    appId: '1:513129336045:android:16c816967281e45f9210e4',
    messagingSenderId: '513129336045',
    projectId: 'alesco-hotelio',
    storageBucket: 'alesco-hotelio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOsmu-urxSeaXRQ0V78PXxv-gwDMHbjE',
    appId: '1:513129336045:ios:122a407c961a628d9210e4',
    messagingSenderId: '513129336045',
    projectId: 'alesco-hotelio',
    storageBucket: 'alesco-hotelio.appspot.com',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwOsmu-urxSeaXRQ0V78PXxv-gwDMHbjE',
    appId: '1:513129336045:ios:122a407c961a628d9210e4',
    messagingSenderId: '513129336045',
    projectId: 'alesco-hotelio',
    storageBucket: 'alesco-hotelio.appspot.com',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY46d_yLZRGNRzhGOJHbg3nWWgBVoj52M',
    appId: '1:513129336045:web:a113f4de2092613d9210e4',
    messagingSenderId: '513129336045',
    projectId: 'alesco-hotelio',
    authDomain: 'alesco-hotelio.firebaseapp.com',
    storageBucket: 'alesco-hotelio.appspot.com',
    measurementId: 'G-KGNG0QSD26',
  );

}